use crate::{Cursor, DecodeError};

/// Signature of every `OpenCarpanel` SCS bridge datagram.
pub const BRIDGE_MAGIC: [u8; 4] = *b"OCP\0";

/// Current major version of the SCS bridge wire protocol.
pub const BRIDGE_PROTOCOL_VERSION: u8 = 1;

/// Wire identifier for Euro Truck Simulator 2.
pub const ETS2_GAME_ID: u8 = 1;

/// Wire identifier for American Truck Simulator.
pub const ATS_GAME_ID: u8 = 2;

/// Exact byte length of a v1 bridge datagram.
pub const BRIDGE_PACKET_LEN: usize = 44;

/// SCS game carried by one bridge packet.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BridgeGame {
    /// Euro Truck Simulator 2.
    Ets2,
    /// American Truck Simulator.
    Ats,
}

impl BridgeGame {
    /// Returns the stable v1 wire value.
    #[must_use]
    pub const fn wire_id(self) -> u8 {
        match self {
            Self::Ets2 => ETS2_GAME_ID,
            Self::Ats => ATS_GAME_ID,
        }
    }

    fn from_wire(value: u8) -> Result<Self, DecodeError> {
        match value {
            ETS2_GAME_ID => Ok(Self::Ets2),
            ATS_GAME_ID => Ok(Self::Ats),
            actual => Err(DecodeError::UnsupportedGame {
                expected: 0,
                actual,
            }),
        }
    }
}

/// Fully validated v1 state emitted by the bundled SCS SDK plugin.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct BridgePacket {
    /// Game that loaded the plugin.
    pub game: BridgeGame,
    /// Per-plugin-initialization session nonce.
    pub session_nonce: u64,
    /// Monotonic frame sequence generated by the plugin.
    pub frame_sequence: u32,
    /// Signed speedometer speed in metres per second.
    pub speed_mps: f32,
    /// Current engine RPM.
    pub rpm: f32,
    /// Configured RPM limit, or zero while unknown.
    pub rpm_max: f32,
    /// Gear shown by the in-game dashboard.
    pub displayed_gear: i32,
    /// Effective simulation throttle in 0..=1.
    pub throttle: f32,
    /// Effective simulation brake in 0..=1.
    pub brake: f32,
}

impl BridgePacket {
    /// Decodes and validates one exact v1 datagram.
    ///
    /// # Errors
    ///
    /// Rejects unsupported signatures, versions, games, flags, lengths, and
    /// any invalid numeric field without retaining raw bytes.
    pub fn decode(datagram: &[u8]) -> Result<Self, DecodeError> {
        let mut cursor = Cursor::new(datagram);
        let magic = cursor.read_array()?;
        if magic != BRIDGE_MAGIC {
            return Err(DecodeError::UnsupportedMagic { actual: magic });
        }

        let version = cursor.read_u8()?;
        if version != BRIDGE_PROTOCOL_VERSION {
            return Err(DecodeError::UnsupportedVersion {
                expected: BRIDGE_PROTOCOL_VERSION,
                actual: version,
            });
        }

        let game = BridgeGame::from_wire(cursor.read_u8()?)?;
        let flags = cursor.read_u8()?;
        let reserved = cursor.read_u8()?;
        if flags != 0 || reserved != 0 {
            return Err(DecodeError::UnsupportedFlags { flags, reserved });
        }
        if datagram.len() != BRIDGE_PACKET_LEN {
            return Err(DecodeError::InvalidLength {
                expected: BRIDGE_PACKET_LEN,
                actual: datagram.len(),
            });
        }

        let packet = Self {
            game,
            session_nonce: cursor.read_u64_le()?,
            frame_sequence: cursor.read_u32_le()?,
            speed_mps: cursor.read_f32_le()?,
            rpm: cursor.read_f32_le()?,
            rpm_max: cursor.read_f32_le()?,
            displayed_gear: cursor.read_i32_le()?,
            throttle: cursor.read_f32_le()?,
            brake: cursor.read_f32_le()?,
        };
        packet.validate_numbers()?;
        Ok(packet)
    }

    fn validate_numbers(self) -> Result<(), DecodeError> {
        finite("speed_mps", self.speed_mps)?;
        rpm("rpm", self.rpm)?;
        rpm("rpm_max", self.rpm_max)?;
        normalized("throttle", self.throttle)?;
        normalized("brake", self.brake)
    }
}

fn finite(field: &'static str, value: f32) -> Result<(), DecodeError> {
    if value.is_finite() {
        Ok(())
    } else {
        Err(DecodeError::NonFiniteValue { field })
    }
}

fn rpm(field: &'static str, value: f32) -> Result<(), DecodeError> {
    if value.is_finite() && (0.0..=f32::from(u16::MAX)).contains(&value) {
        Ok(())
    } else if !value.is_finite() {
        Err(DecodeError::NonFiniteValue { field })
    } else {
        Err(DecodeError::InvalidRpm { field, value })
    }
}

fn normalized(field: &'static str, value: f32) -> Result<(), DecodeError> {
    if value.is_finite() && (0.0..=1.0).contains(&value) {
        Ok(())
    } else if !value.is_finite() {
        Err(DecodeError::NonFiniteValue { field })
    } else {
        Err(DecodeError::InvalidNormalizedValue { field, value })
    }
}
